name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**' # Trigger only on frontend changes

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies and Build
        working-directory: ./packages/client
        run: npm ci && npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_JIRA_BASE_URL: ${{ secrets.VITE_JIRA_BASE_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOAT_PROJECT_465601 }}' # This secret was created for you
          channelId: live
          projectId: goat-project-465601