name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
      - development
          paths:
      - 'packages/server/**'
  workflow_dispatch: {}

env:
  PROJECT_ID: goat-project-465601 # Your GCP Project ID
  SERVICE_NAME: goat-backend      # Your Cloud Run service name
  REGION: asia-southeast2         # Your service region

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      # This step now waits for the build to finish
      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit packages/server --tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # This step now uses the correct 'flags' input
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE_NAME }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}:${{ github.sha }}'
          flags: '--allow-unauthenticated'